### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-includepatriciamartinez#1]
Buen trabajo @includepatriciamartinez !

### Algunas pistas para acabarlo:

- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Este componente no recibe children https://github.com/Adalab/modulo-3-evaluacion-intermedia-includepatriciamartinez/blob/master/src/components/PokeList.js#L12
- [x] Cuidado con esta ruta https://github.com/Adalab/modulo-3-evaluacion-intermedia-includepatriciamartinez/blob/master/src/components/PokeList.js#L2

### Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by includepatriciamartinez** [comment]
Hola Miguel, he corregido los cuatro puntos primeros y las otras mejoras en cuanto pase el módulo de React pondré en orden mi porfolio y esto será una de las cosas que haré. Gracias.
